name: Print Message Workflow

on:
  workflow_dispatch:
    inputs:
      myvalue:
        description:'Value'
        required:true
        default:'dev'
      environment:
        description: "Environment to deploy"
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - uat
          - prod
          - mgmt
      aws_region:
        description: "AWS Region to connect to"
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - 'us-east-1'
          - 'us-west-2'
      tenant:
        description: "AWS Tenant"
        required: true
        default: 'Acuity'
        type: choice
        options:
          - 'Acuity'
          - 'Ohio'
 
permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print a message
      run: echo "Hello, world!"
